Jwl 20220803 Assignment 1A
UKJWL/MyCodeChallenge pull request #2
Opened 2022-08-03 14:28 UTC by UKJWL

This is my pull request for you to review my implementation. I chose to use profiles to give user's specific access to the mainly digital application and it's objects.  I found that permission sets were less suited because they are used to extend a user's access on top of a profile.  Using profiles also allowed me to put restrictions in place and only allow users to the Mainly Digital application.

2022-08-03 16:12 UTC, UKJWL commented
So I've come to realise that when I was testing my profiles I couldn't see the records belonging to each object, if I'm correct it's because the field level security for the objects were already established because my profiles were created after the fact. I'm happy to change it, but as you said changing before a demo is unwise so I'll change that afterwards.

2022-08-03 16:24 UTC, keirbowden requested changes
Couple of things to look at.

2022-08-03 16:24 UTC, keirbowden commented on force-app/main/default/profiles/Mainly Digital System Adminstrator.profile-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This name is a bit misleading - they aren't the System Administrator - in Salesforce that would indicate they can create users, apps, custom objects. Instead they are the Onboarding Administrator or if you are keeping with the other names, Mainly Digital Administrator.

2022-08-03 16:24 UTC, keirbowden commented on force-app/main/default/profiles/Mainly Digital Candidate.profile-meta.xml
> +    <description>A candidate role for the mainly digital application.</description>
This is a profile not a role - roles are a different concept in Salesforce. This description is also just restating the name of the profile. A better description would be to explain what a candidate can do - e.g. they are allowed to see their journey and steps but none of the template information.

2022-08-04 10:47 UTC, UKJWL commented on force-app/main/default/profiles/Mainly Digital System Adminstrator.profile-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I understand, I've changed to Onboarding Administrator.

2022-08-04 10:53 UTC, UKJWL commented on force-app/main/default/profiles/Mainly Digital Candidate.profile-meta.xml
> +    <description>A candidate role for the mainly digital application.</description>
I had wrote that in a different context, I was describing it as a job role, but yes I can completely see what you mean because of the significance of roles in salesforce, and I suppose it's a technical description used for technical reference, similar to commenting your code for example, and if someone else saw that description it would cause confusion. Changed, and have described what the profile does.

2022-08-04 10:55 UTC, UKJWL commented on force-app/main/default/profiles/Mainly Digital Candidate.profile-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Thanks, I was unsure on the naming convention, how and what to name things, cleared that up. I've changed the names regardless to Onboarding ____ , makes much more sense that way.

2022-08-05 16:20 UTC, keirbowden reviewed
Looks good - book the show and tell and assuming there are no changes required from that I'll approve.

2022-08-05 16:22 UTC, UKJWL commented
Great. Thank you.


Joshua Love
Graduate Consultant
+44 7791858815
***@***.***
brightgen.com

[https://www2.brightgen.com/l/69832/2022-02-16/k4sxl3/69832/1645013961em3Ztb5O/BrightGen_Primary_logo_horizontal___1_.png]
[https://www2.brightgen.com/l/69832/2022-02-16/k4sxl5/69832/16450090905FcQzvfN/2016_2017__2019_awards_.png] [https://www2.brightgen.com/l/69832/2022-01-11/jxqty3/69832/1656331310vwWKBiME/Salesforce_Partner_Badge_Since_2007_RGB.png]

[https://www2.brightgen.com/l/69832/2022-02-18/k5v842/69832/1645182313EuruzQMG/Combined_ISO_Logos_125px.png]<http://www.brightgen.com>

Registered Office: BrightGen Ltd, Ginetta House, 155-157 Newland Street, Witham, CM8 1BE
A company registered in England and Wales under Registration No. 5994605

________________________________
From: Keir Bowden ***@***.***>
Sent: 05 August 2022 17:20
To: UKJWL/MyCodeChallenge ***@***.***>
Cc: Joshua Love (BrightGen) ***@***.***>; Author ***@***.***>
Subject: Re: [UKJWL/MyCodeChallenge] Jwl 20220803 Assignment 1A (PR #2)


@keirbowden commented on this pull request.

Looks good - book the show and tell and assuming there are no changes required from that I'll approve.

—
Reply to this email directly, view it on GitHub<https://github.com/UKJWL/MyCodeChallenge/pull/2#pullrequestreview-1063589824>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZ2TYHO4HBXK2K2HUAOMTO3VXU5NHANCNFSM55PCNHXA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

This email is intended only for the person or entity to which it is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. Dissemination, distribution, or copying of this email or the information herein by anyone other than the intended recipient, or an employee or agent responsible for delivering the message to the intended recipient, is prohibited. If you have received this email in error, please notify the sender immediately.

2022-08-11 10:24 UTC, keirbowden approved these changes
Merge away.

2022-08-22 08:45 UTC, merged