Assignment 3 Pull Request
UKJWL/MyCodeChallenge pull request #4
Opened 2022-11-17 11:42 UTC by UKJWL

2022-11-17 18:20 UTC, Drywkenway requested changes

2022-11-17 18:20 UTC, Drywkenway commented on force-app/main/default/lwc/timeline/timeline.html
> +                                  <h3 class="slds-tile__title slds-truncate" title="Journey Name">
why is the title journey name? im assuming you meant task name.

2022-11-17 18:20 UTC, Drywkenway commented on force-app/main/default/lwc/timeline/timeline.html
> +                                  <h3 class="slds-tile__title slds-truncate" title="Journey Name">
why is the title journey name?

2022-11-17 18:20 UTC, Drywkenway commented on force-app/main/default/lwc/timeline/timeline.html
> +                                  <h3 class="slds-tile__title slds-truncate" title="Journey Name">
why is the title journey name?

2022-11-17 18:20 UTC, Drywkenway commented on force-app/main/default/lwc/timeline/timeline.js
> +    handleClick(){
what purpose does this method serve?

2022-11-17 18:27 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.js
> +    handleClick(){
Was an attempt at something else, deprecated now, so has been deleted.

2022-11-17 18:28 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                  <h3 class="slds-tile__title slds-truncate" title="Journey Name">
Changed.

2022-11-17 18:29 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                  <h3 class="slds-tile__title slds-truncate" title="Journey Name">
Copying and pasting the card lead to an oversight, changed.

2022-11-17 18:29 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                  <h3 class="slds-tile__title slds-truncate" title="Journey Name">
Copying and pasting the card lead to an oversight, changed.

2022-11-17 18:36 UTC, UKJWL commented on force-app/main/default/lwc/onboardingDateUpdate/onboardingDateUpdate.html
> +    <lightning-quick-action-panel header="Update Onboarding Start Date">
So custom label's isn't something I've really heard of. I've gone away and looked into them and I see why you would use them. I have a question. When you import the labels in your .js file, do you import all labels individually, or can you import them all at once?

2022-11-18 10:18 UTC, UKJWL commented on force-app/main/default/lwc/onboardingDateUpdate/onboardingDateUpdate.js
> +            new ShowToastEvent({
changed

2022-11-18 10:18 UTC, UKJWL commented on force-app/main/default/lwc/onboardingDateUpdate/onboardingDateUpdate.html
> +                label="Save"
changed

2022-11-18 10:19 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                        <template if:true={CompletedTasks}>
Changed

2022-11-18 10:19 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                    <p style = "font-weight: 600;">Task Name:</p>
Changed

2022-11-18 10:19 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                    <p style = "font-weight: 600;">Task Name:</p>
changed

2022-11-18 10:19 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +           <lightning-tab label="Overdue" value="Overdue" title = "Overdue">
changed

2022-11-18 10:19 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +          <lightning-tab label="Completed" value="Completed" title = "Completed">
changed

2022-11-18 10:20 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +          <lightning-tab label="In Progress" value="InProgress" title = "In Progress">
changed

2022-11-18 10:20 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                    <p class="slds-truncate" title="Esimated Completion Date:">Esimated Completion Date:</p>
changed

2022-11-18 10:20 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                    <p class="slds-truncate" title="Esimated Completion Date:">Esimated Completion Date:</p>
changed

2022-11-18 10:20 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                    <p class="slds-truncate" title="Esimated Completion Date:">Esimated Completion Date:</p>
changed

2022-11-18 10:20 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                                    <p style = "font-weight: 600;">Task Name:</p>
changed

2022-11-18 10:20 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +    <lightning-card title="Your Journey Progress">
changed

2022-11-18 10:24 UTC, UKJWL commented on force-app/main/default/lwc/timeline/timeline.html
> +                   <template for:each={CompletedTasks} for:item="rec">
Changed

2022-11-18 14:46 UTC, Drywkenway approved these changes

2022-11-18 14:47 UTC, merged